[package]
name = "sphere"
version = "0.1.0"
authors = ["956697547@qq.com <956697547@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vec3 = {path = "../vec3"}
ray = {path = "../ray"}